/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authenticatedManageRouteRouteImport } from './routes/(authenticated)/manage/route'
import { Route as authenticatedDashboardRouteRouteImport } from './routes/(authenticated)/dashboard/route'
import { Route as authenticatedDashboardIndexRouteImport } from './routes/(authenticated)/dashboard/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as authenticatedManageUsers1RouteImport } from './routes/(authenticated)/manage/users1'
import { Route as authenticatedManageUsersRouteImport } from './routes/(authenticated)/manage/users'
import { Route as authenticatedDashboardAccountAccountViewRouteImport } from './routes/(authenticated)/dashboard/account/$accountView'

const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authenticatedManageRouteRoute =
  authenticatedManageRouteRouteImport.update({
    id: '/manage',
    path: '/manage',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedDashboardRouteRoute =
  authenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedDashboardIndexRoute =
  authenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedManageUsers1Route =
  authenticatedManageUsers1RouteImport.update({
    id: '/users1',
    path: '/users1',
    getParentRoute: () => authenticatedManageRouteRoute,
  } as any)
const authenticatedManageUsersRoute =
  authenticatedManageUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => authenticatedManageRouteRoute,
  } as any)
const authenticatedDashboardAccountAccountViewRoute =
  authenticatedDashboardAccountAccountViewRouteImport.update({
    id: '/account/$accountView',
    path: '/account/$accountView',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof authenticatedRouteRouteWithChildren
  '/dashboard': typeof authenticatedDashboardRouteRouteWithChildren
  '/manage': typeof authenticatedManageRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/api/health': typeof ApiHealthRoute
  '/manage/users': typeof authenticatedManageUsersRoute
  '/manage/users1': typeof authenticatedManageUsers1Route
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard/': typeof authenticatedDashboardIndexRoute
  '/dashboard/account/$accountView': typeof authenticatedDashboardAccountAccountViewRoute
}
export interface FileRoutesByTo {
  '/': typeof authenticatedRouteRouteWithChildren
  '/manage': typeof authenticatedManageRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/api/health': typeof ApiHealthRoute
  '/manage/users': typeof authenticatedManageUsersRoute
  '/manage/users1': typeof authenticatedManageUsers1Route
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard': typeof authenticatedDashboardIndexRoute
  '/dashboard/account/$accountView': typeof authenticatedDashboardAccountAccountViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(authenticated)/dashboard': typeof authenticatedDashboardRouteRouteWithChildren
  '/(authenticated)/manage': typeof authenticatedManageRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/api/health': typeof ApiHealthRoute
  '/(authenticated)/manage/users': typeof authenticatedManageUsersRoute
  '/(authenticated)/manage/users1': typeof authenticatedManageUsers1Route
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/(authenticated)/dashboard/': typeof authenticatedDashboardIndexRoute
  '/(authenticated)/dashboard/account/$accountView': typeof authenticatedDashboardAccountAccountViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/manage'
    | '/login'
    | '/signup'
    | '/api/health'
    | '/manage/users'
    | '/manage/users1'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/dashboard/'
    | '/dashboard/account/$accountView'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/manage'
    | '/login'
    | '/signup'
    | '/api/health'
    | '/manage/users'
    | '/manage/users1'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/dashboard'
    | '/dashboard/account/$accountView'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(authenticated)'
    | '/(authenticated)/dashboard'
    | '/(authenticated)/manage'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/api/health'
    | '/(authenticated)/manage/users'
    | '/(authenticated)/manage/users1'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/(authenticated)/dashboard/'
    | '/(authenticated)/dashboard/account/$accountView'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authenticated)': {
      id: '/(authenticated)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(authenticated)/manage': {
      id: '/(authenticated)/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof authenticatedManageRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/dashboard': {
      id: '/(authenticated)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authenticatedDashboardRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/dashboard/': {
      id: '/(authenticated)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof authenticatedDashboardIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/manage/users1': {
      id: '/(authenticated)/manage/users1'
      path: '/users1'
      fullPath: '/manage/users1'
      preLoaderRoute: typeof authenticatedManageUsers1RouteImport
      parentRoute: typeof authenticatedManageRouteRoute
    }
    '/(authenticated)/manage/users': {
      id: '/(authenticated)/manage/users'
      path: '/users'
      fullPath: '/manage/users'
      preLoaderRoute: typeof authenticatedManageUsersRouteImport
      parentRoute: typeof authenticatedManageRouteRoute
    }
    '/(authenticated)/dashboard/account/$accountView': {
      id: '/(authenticated)/dashboard/account/$accountView'
      path: '/account/$accountView'
      fullPath: '/dashboard/account/$accountView'
      preLoaderRoute: typeof authenticatedDashboardAccountAccountViewRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface authenticatedDashboardRouteRouteChildren {
  authenticatedDashboardIndexRoute: typeof authenticatedDashboardIndexRoute
  authenticatedDashboardAccountAccountViewRoute: typeof authenticatedDashboardAccountAccountViewRoute
}

const authenticatedDashboardRouteRouteChildren: authenticatedDashboardRouteRouteChildren =
  {
    authenticatedDashboardIndexRoute: authenticatedDashboardIndexRoute,
    authenticatedDashboardAccountAccountViewRoute:
      authenticatedDashboardAccountAccountViewRoute,
  }

const authenticatedDashboardRouteRouteWithChildren =
  authenticatedDashboardRouteRoute._addFileChildren(
    authenticatedDashboardRouteRouteChildren,
  )

interface authenticatedManageRouteRouteChildren {
  authenticatedManageUsersRoute: typeof authenticatedManageUsersRoute
  authenticatedManageUsers1Route: typeof authenticatedManageUsers1Route
}

const authenticatedManageRouteRouteChildren: authenticatedManageRouteRouteChildren =
  {
    authenticatedManageUsersRoute: authenticatedManageUsersRoute,
    authenticatedManageUsers1Route: authenticatedManageUsers1Route,
  }

const authenticatedManageRouteRouteWithChildren =
  authenticatedManageRouteRoute._addFileChildren(
    authenticatedManageRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedDashboardRouteRoute: typeof authenticatedDashboardRouteRouteWithChildren
  authenticatedManageRouteRoute: typeof authenticatedManageRouteRouteWithChildren
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedDashboardRouteRoute:
    authenticatedDashboardRouteRouteWithChildren,
  authenticatedManageRouteRoute: authenticatedManageRouteRouteWithChildren,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
